language: go

go:
  - 1.23.x
  - 1.24.x

services:
  - docker

script:
  - docker pull confluentinc/confluent-local:8.1.1
  - go build -o kafka-idle-topics ./cmd/kafka-idle-topics/*
  - cd cmd/kafka-idle-topics/
  - go test

addons:
  sonarcloud:
    organization: "Ivan Kunz"
